<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?><package format="3">
  <name>rko_slam</name>
  <version>0.0.1</version>
  <description>ROS2 LiDAR-inertial SLAM for your odometry: drift correction and multi-session alignment</description>
  <maintainer email="rm.meher97@gmail.com">Meher Malladi</maintainer>
  <license>MIT</license>
  <url type="website">https://prbonn.github.io/rko_slam/</url>
  <url type="repository">https://github.com/PRBonn/rko_slam</url>
  <url type="bugtracker">https://github.com/PRBonn/rko_slam/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>eigen</depend>
  <depend>sophus</depend>
  <depend>spdlog</depend>
  <depend>nanoflann</depend>
  <depend>robin-map-dev</depend>
  <depend>yaml-cpp</depend>
  <depend>libopencv-dev</depend>
  <depend version_gte="0.4.1">rko_lio</depend>

  <test_depend>catch2</test_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>builtin_interfaces</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>rosbag2_storage</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <rosdoc2>rosdoc2.yaml</rosdoc2>
  </export>
</package>
